controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_nbp_average_currency:
    path: /currency
    controller: App\Controller\NBPAverageCurrencyRateCheckerController::getAverageCurrencyRateInDateRange
